# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  # config.vbguest.auto_update = true
  config.vm.network "private_network", type: "dhcp"

  config.vm.box = 'mesosphere/dcos-centos-virtualbox'

  config.vm.provision "shell", path: "provision.sh"
end

